//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIPT.Track.dacws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSACShowResultSoap", Namespace="http://tempuri.org/")]
    public partial class WSACShowResult : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback ShowMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowMessageForCusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSerialByDacCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataQueryRecOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSACShowResult() {
            this.Url = global::PIPT.Track.Properties.Settings.Default.PIPT_Track_dacws_WSACShowResult;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ShowMessageCompletedEventHandler ShowMessageCompleted;
        
        /// <remarks/>
        public event ShowMessageForCusCompletedEventHandler ShowMessageForCusCompleted;
        
        /// <remarks/>
        public event GetSerialByDacCodeCompletedEventHandler GetSerialByDacCodeCompleted;
        
        /// <remarks/>
        public event GetDataQueryRecCompletedEventHandler GetDataQueryRecCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DacResultInfo ShowMessage(string sDacCode, string ipc) {
            object[] results = this.Invoke("ShowMessage", new object[] {
                        sDacCode,
                        ipc});
            return ((DacResultInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ShowMessageAsync(string sDacCode, string ipc) {
            this.ShowMessageAsync(sDacCode, ipc, null);
        }
        
        /// <remarks/>
        public void ShowMessageAsync(string sDacCode, string ipc, object userState) {
            if ((this.ShowMessageOperationCompleted == null)) {
                this.ShowMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowMessageOperationCompleted);
            }
            this.InvokeAsync("ShowMessage", new object[] {
                        sDacCode,
                        ipc}, this.ShowMessageOperationCompleted, userState);
        }
        
        private void OnShowMessageOperationCompleted(object arg) {
            if ((this.ShowMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowMessageCompleted(this, new ShowMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowMessageForCus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DacResultInfo ShowMessageForCus(string sDacCode, string ipc) {
            object[] results = this.Invoke("ShowMessageForCus", new object[] {
                        sDacCode,
                        ipc});
            return ((DacResultInfo)(results[0]));
        }
        
        /// <remarks/>
        public void ShowMessageForCusAsync(string sDacCode, string ipc) {
            this.ShowMessageForCusAsync(sDacCode, ipc, null);
        }
        
        /// <remarks/>
        public void ShowMessageForCusAsync(string sDacCode, string ipc, object userState) {
            if ((this.ShowMessageForCusOperationCompleted == null)) {
                this.ShowMessageForCusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowMessageForCusOperationCompleted);
            }
            this.InvokeAsync("ShowMessageForCus", new object[] {
                        sDacCode,
                        ipc}, this.ShowMessageForCusOperationCompleted, userState);
        }
        
        private void OnShowMessageForCusOperationCompleted(object arg) {
            if ((this.ShowMessageForCusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowMessageForCusCompleted(this, new ShowMessageForCusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSerialByDacCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DacResultInfo GetSerialByDacCode(string sDacCode) {
            object[] results = this.Invoke("GetSerialByDacCode", new object[] {
                        sDacCode});
            return ((DacResultInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetSerialByDacCodeAsync(string sDacCode) {
            this.GetSerialByDacCodeAsync(sDacCode, null);
        }
        
        /// <remarks/>
        public void GetSerialByDacCodeAsync(string sDacCode, object userState) {
            if ((this.GetSerialByDacCodeOperationCompleted == null)) {
                this.GetSerialByDacCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSerialByDacCodeOperationCompleted);
            }
            this.InvokeAsync("GetSerialByDacCode", new object[] {
                        sDacCode}, this.GetSerialByDacCodeOperationCompleted, userState);
        }
        
        private void OnGetSerialByDacCodeOperationCompleted(object arg) {
            if ((this.GetSerialByDacCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSerialByDacCodeCompleted(this, new GetSerialByDacCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataQueryRec", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDataQueryRec(string fromDate, string toDate, string unitCode, int QueryRecID) {
            object[] results = this.Invoke("GetDataQueryRec", new object[] {
                        fromDate,
                        toDate,
                        unitCode,
                        QueryRecID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataQueryRecAsync(string fromDate, string toDate, string unitCode, int QueryRecID) {
            this.GetDataQueryRecAsync(fromDate, toDate, unitCode, QueryRecID, null);
        }
        
        /// <remarks/>
        public void GetDataQueryRecAsync(string fromDate, string toDate, string unitCode, int QueryRecID, object userState) {
            if ((this.GetDataQueryRecOperationCompleted == null)) {
                this.GetDataQueryRecOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataQueryRecOperationCompleted);
            }
            this.InvokeAsync("GetDataQueryRec", new object[] {
                        fromDate,
                        toDate,
                        unitCode,
                        QueryRecID}, this.GetDataQueryRecOperationCompleted, userState);
        }
        
        private void OnGetDataQueryRecOperationCompleted(object arg) {
            if ((this.GetDataQueryRecCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataQueryRecCompleted(this, new GetDataQueryRecCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DacResultInfo {
        
        private int resultStatusField;
        
        private string unitCodeField;
        
        private string queryModeField;
        
        private string messageField;
        
        private string unitNameField;
        
        private string sMSNoteField;
        
        private long seriesNoField;
        
        /// <remarks/>
        public int ResultStatus {
            get {
                return this.resultStatusField;
            }
            set {
                this.resultStatusField = value;
            }
        }
        
        /// <remarks/>
        public string UnitCode {
            get {
                return this.unitCodeField;
            }
            set {
                this.unitCodeField = value;
            }
        }
        
        /// <remarks/>
        public string QueryMode {
            get {
                return this.queryModeField;
            }
            set {
                this.queryModeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string UnitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
        
        /// <remarks/>
        public string SMSNote {
            get {
                return this.sMSNoteField;
            }
            set {
                this.sMSNoteField = value;
            }
        }
        
        /// <remarks/>
        public long SeriesNo {
            get {
                return this.seriesNoField;
            }
            set {
                this.seriesNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ShowMessageCompletedEventHandler(object sender, ShowMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DacResultInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DacResultInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ShowMessageForCusCompletedEventHandler(object sender, ShowMessageForCusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowMessageForCusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowMessageForCusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DacResultInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DacResultInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetSerialByDacCodeCompletedEventHandler(object sender, GetSerialByDacCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSerialByDacCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSerialByDacCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DacResultInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DacResultInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetDataQueryRecCompletedEventHandler(object sender, GetDataQueryRecCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataQueryRecCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataQueryRecCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591